<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.eztxm</groupId>
        <artifactId>luckprefix-parent</artifactId>
        <version>2.0.0-BETA+10-SNAPSHOT</version>
    </parent>

    <artifactId>luckprefix-modern-paper</artifactId>

    <name>LuckPrefix</name>

    <packaging>jar</packaging>

    <properties>
        <id>luckprefix</id>
        <loader>paper</loader>
        <build.number>dev</build.number>
        <build.name>${id}-${project.version}-${loader}-${build.number}</build.name>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.40</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <finalName>${build.name}</finalName>
                            <artifactSet>
                                <includes>
                                    <include>de.eztxm:luckprefix-common</include>
                                    <include>de.eztxm:ezlib-*</include>
                                    <include>org.json:json</include>
                                    <include>org.bstats:bstats-bukkit</include>
                                </includes>
                            </artifactSet>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>org.bstats:bstats-bukkit</artifact>
                                    <includes>
                                        <include>**</include>
                                    </includes>
                                </filter>
                            </filters>
                            <relocations>
                                <relocation>
                                    <pattern>de.eztxm.ezlib</pattern>
                                    <shadedPattern>de.eztxm.luckprefix.libs.ezlib</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>de.eztxm.common</pattern>
                                    <shadedPattern>de.eztxm.luckprefix.libs.common</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.json</pattern>
                                    <shadedPattern>de.eztxm.luckprefix.libs.json</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.bstats</pattern>
                                    <shadedPattern>de.eztxm.luckprefix.libs.bstats</shadedPattern>
                                </relocation>
                            </relocations>
                            <minimizeJar>true</minimizeJar>
                            <createDependencyReducedPom>true</createDependencyReducedPom>
                            <keepDependenciesWithProvidedScope>true</keepDependenciesWithProvidedScope>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>eztxm-repo</id>
            <url>https://repo.eztxm.de/maven</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.21.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.luckperms</groupId>
            <artifactId>api</artifactId>
            <version>5.5</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>${project.parent.groupId}</groupId>
            <artifactId>luckprefix-common</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.40</version>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>26.0.2-1</version>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>de.eztxm</groupId>
            <artifactId>ezlib-database-mariadb</artifactId>
            <version>1.0-ALPHA11</version>
        </dependency>
        <dependency>
            <groupId>de.eztxm</groupId>
            <artifactId>ezlib-database-sqlite</artifactId>
            <version>1.0-ALPHA11</version>
        </dependency>
        <dependency>
            <groupId>de.eztxm</groupId>
            <artifactId>ezlib-database-mongodb</artifactId>
            <version>1.0-ALPHA11</version>
        </dependency>
        <dependency>
            <groupId>de.eztxm</groupId>
            <artifactId>ezlib-common</artifactId>
            <version>1.0-ALPHA11</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20250517</version>
        </dependency>
        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bukkit</artifactId>
            <version>3.1.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

</project>