#  _               _    ____            __ _
# | |   _   _  ___| | _|  _ \ _ __ ___ / _(_)_  __
# | |  | | | |/ __| |/ / |_) | '__/ _ \ |_| \ \/ /
# | |__| |_| | (__|   <|  __/| | |  __/  _| |>  <
# |_____\__,_|\___|_|\_\_|   |_|  \___|_| |_/_/\_\
# Modern 2.0.0 | by ezTxmMC

# The permission to write with color-codes in the chat
ColoredPermission: "luckprefix.colored"

# Automatically reload of the config
AutoReloadConfig: false

# The time of updating the prefix in the tablist in seconds
UpdateTime: 10

# The group values. Gradient is optional
Groups:
  # The name of the group
  default:
    # Prefix, Suffix, Tabformat and Chatformat are only works with adventure minimessage format
    Prefix: "<gray>Player"
    Suffix: ""
    Tabformat: "<prefix> <dark_gray>- <gray><player>"
    Chatformat: "<prefix> <dark_gray>- <gray><player> <dark_gray>%>><gray><message>"
    SortID: 1
    Color: "gray"
