name: ${project.name}
version: ${project.version}
main: de.eztxm.luckprefix.LuckPrefix
author: ezTxmMC
api-version: '1.20'
description: The luckperms addon for tab- and chat-prefixes on the market.
website: https://eztxm.de

depend:
  - LuckPerms
