#  _               _    ____            __ _
# | |   _   _  ___| | _|  _ \ _ __ ___ / _(_)_  __
# | |  | | | |/ __| |/ / |_) | '__/ _ \ |_| \ \/ /
# | |__| |_| | (__|   <|  __/| | |  __/  _| |>  <
# |_____\__,_|\___|_|\_\_|   |_|  \___|_| |_/_/\_\
# Modern ${project.version} | by ezTxmMC

# The permission to write with color-codes in the chat
ColoredPermission: "luckprefix.coloredmessages"

# Automatically reload of the config
AutoReloadConfig:
  # If true it automatically reloads the config after the interval
  Enabled: false
  # The interval in seconds to reload the config
  Interval: 10

# The time of updating the prefix in seconds
UpdateTime: 5

# Shows the nametag above the players
ShowNameTags: true

# The message that shows the information that a new update is available
UpdateAvailableMessage: true

# If true it send a warning for each group that not be in groups.yml
Warning-If-Group-Can-Not-Loaded: true

# If true it will automatically insert not existing groups into the groups.yml or as entry in the database
# ONLY REMOVE THIS IF YOU KNOW WHAT YOU ARE DOING! ELSE IT WILL DISPLAY ERRORS!
Auto-Add-Group: true
